### ISSUE TITLE
请问可以提供一下模型嘛？

### ISSUE THREAD

**Issue by lyccol** [wuyangzhang/elf#5]
prediction_model_paths: Tuple[str] = (
        './prediction/model/outputs/lstm_single_checkpoint40.pth',
        './prediction/model/outputs/attn_lstm_checkpoint30.pth',
    )
感谢

**Comment by wuyangzhang** [comment]
Please see the model in https://github.com/wuyangzhang/elf/tree/master/python/rp_predict/model/outputs
